### ISSUE TITLE
PUT instead of POST

### ISSUE THREAD

**Issue by thedeviousdev** [RusticiSoftware/TinCanPHP#103]
Is there a way to change a statement to send via PUT instead of POST? The particular LRS I am working with requires PUT to be the method of transmission.

**Comment by brianjmiller** [comment]
Probably worth noting that you are working with a non-spec conforming LRS if it doesn't allow POSTing of a statement.

Having said that, you can trigger a PUT to the statements resource by assigning the statement an `id` before making the call to `saveStatement`. The easiest way to do this with the library is to call the Statement instance's `stamp` method after construction. This will assign both an `id` and a `timestamp` value.
