### ISSUE TITLE
If-None-Match header missing

### ISSUE THREAD

**Issue by GinovskiIvan** [RusticiSoftware/TinCanPHP#104]
Hi there,
I am trying to integrate the tincan library with an application of mine and I am looking to create an activity profile on a xAPI Learning Record Store. Now, when trying to save this new activity, there is an error popping up, something like: If-None-Match & If-Match headers are both missing. This is due to creating the profile for the first time and I want to set a header If-None-Match="*", but there is no possibility for that. Now I was looking through the **RemoteLRS** class and I saw that there is an optional header to put the If-Match into the sending statement when saving the activity profile, could you implement something like that for the If-None-Match header as well?

`if (func_num_args() > 3) {
            $options = func_get_arg(3);
            if (isset($options)) {
                if (isset($options['contentType'])) {
                    $requestCfg['headers']['Content-Type'] = $contentType = $options['contentType'];
                }
                if (isset($options['etag'])) {
                    $requestCfg['headers']['If-Match'] = $options['etag'];
                }
            }
        }`

There would need to be an additional else if stating:

`if (isset($options['If-None-Match'])) {
      $requestCfg['headers']['If-None-Match'] = $options['If-None-Match'];
}`

Is this doable? Thank you in advance.

**Comment by garemoko** [comment]
I believe this is the same issue as is addressed by this PR: https://github.com/RusticiSoftware/TinCanPHP/pull/90

**Comment by brianjmiller** [comment]
Thanks @garemoko for pointing that out. I've gone ahead and merged the PR and cut release 1.1.1. We'll be trying to get the other PRs cleaned up and merged in the coming months. This one was small enough and had no conflicts that it could go in easily.
