### ISSUE TITLE
Utils get timestamp returns an invalid timestamp

### ISSUE THREAD

**Issue by garemoko** [RusticiSoftware/TinCanPHP#22]
https://github.com/RusticiSoftware/TinCanPHP/blob/master/src/Util.php#L73

Guess I missed that one.

**Comment by garemoko** [comment]
Do we even need the util function when we can just go: 

```(new \DateTime())->format('c')```

**Comment by brianjmiller** [comment]
At the time my belief was that DateTime couldn't handle sub-seconds which is probably why that exists that way. Recent development makes me think that isn't the case so we can revisit. I don't think overall the helper method in a utils lib is a bad thing, and most of the other libs will provide something similar as well. Providing a public interface also makes it easy for us to control the implementation in cases where we find a better solution, potentially like this one.

**Comment by brianjmiller** [comment]
Sorry, or were you saying that it *is* returning an invalid timestamp?

**Comment by garemoko** [comment]
Yeh, the timestamp being returned by this function is invalid. The same issue as we addressed in https://github.com/RusticiSoftware/TinCanPHP/commit/14464f7522b8002d877aa03b2951d923576194a0 but we (I) missed that function.

**Comment by brianjmiller** [comment]
Sample coming out of that function: `2015-02-04T20:12:19.358040+0000` I'm not seeing anything invalid, other than over precision which will get dropped.

**Comment by garemoko** [comment]
Should be ```2015-02-04T20:12:19.358040+00:00``` #spotthedifference

Note the colon 3rd from last character.

**Comment by garemoko** [comment]
I picked this up because Cloud rejected it. See http://php.net/manual/en/class.datetime.php#116085 and of course http://tincanapi.com/2014/12/18/getting-details-right-iso-8601-timestamps/ :-)

**Comment by brianjmiller** [comment]
Bah, keep forgetting which way this goes. Cool.
