### ISSUE TITLE
Allow headers to be set when querying statements

### ISSUE THREAD

**Issue by garemoko** [RusticiSoftware/TinCanPHP#26]
It would be helpful to be able to pass options to ```sendRequest``` via ```queryStatements```, for example headers such as ```Accept-language```. 

The code might look something like (although $options should really be optional): 

```
    public function queryStatementsWithOptions($query, $options) {
        $requestCfg = array(
            'params' => $this->_queryStatementsRequestParams($query),
        );

        $response = $this->sendRequest('GET', 'statements', $requestCfg, $options);

        if ($response->success) {
            $this->_queryStatementsResult($response);
        }

        return $response;
    }
```

**Comment by garemoko** [comment]
Actually, we can just add 
```
'headers', 
'params',
``` 

to the list https://github.com/RusticiSoftware/TinCanPHP/blob/master/src/RemoteLRS.php#L334 to the same effect.

**Comment by brianjmiller** [comment]
This was slipped in as part of #28 but wouldn't have worked as indicated because those two options end up one level deeper than is intended. They would have to get handled at the `queryStatements` level so I backed it out as part of #41.
