### ISSUE TITLE
Consider deleting "TODO: Group"

### ISSUE THREAD

**Issue by garemoko** [RusticiSoftware/TinCanPHP#29]
The agent profile methods have TODOs indicating they should support groups in addition to agents. 

See the discussion here: https://github.com/adlnet/xAPI-Spec/issues/682

Depending on the outcome, we should remove those TODOs.

**Comment by brianjmiller** [comment]
Will take this on as the last round once the other PRs land before the next release.

**Comment by brianjmiller** [comment]
https://github.com/RusticiSoftware/TinCanPHP/commit/3eba26fa5526fe74ba6b449abc43f235c6fd8884
