### ISSUE TITLE
Get more (all) statements

### ISSUE THREAD

**Issue by dailez** [RusticiSoftware/TinCanPHP#33]
I have a LRS with more than 100 statements. In this case, queryStatements(...) only return the first 100 statements and returns a moreUrl to get more statements. However, I did not manage to get the remaining statements. Instead, it allways returns an error. Can you give a working example? This would really help. Many thanks in advance!

Christian

**Comment by garemoko** [comment]
Here's an example: 
```
//Assuming you have queried the LRS for statements and $queryStmtsResponse is the LRS response object.
// $lrs is your TinCanPHP LRS object

$queryStatements = $queryStmtsResponse->content->getStatements();
$moreStatementsURL = $queryStmtsResponse->content->getMore();
while (!is_null($moreStatementsURL)) {
    $moreStmtsResponse = $lrs->moreStatements($moreStatementsURL);
    $moreStatements = $moreStmtsResponse->content->getStatements();
    $moreStatementsURL = $moreStmtsResponse->content->getMore();
    //Note, due to the structure of the arrays, array_merge does not work you might expect, so do this instead:
    foreach ($moreStatements as $moreStatement) {
        array_push($queryStatements, $moreStatement);
    }
}
```

Also take a look at https://github.com/RusticiSoftware/TinCanPHP/pull/17 which is an attempt to add functionality to return all the statements. If somebody were to finish that PR off and get it merged, that would solve your issue too I believe.

**Comment by dailez** [comment]
Thank you very much

**Comment by garemoko** [comment]
No problem!
