### ISSUE TITLE
{"score":{"raw":0}} gets sent as {"score":[]} 

### ISSUE THREAD

**Issue by garemoko** [RusticiSoftware/TinCanPHP#34]
@ryansmih94 reported that {"score":{"raw":0}} gets sent as {"score":[]} 

I've not tested myself.

**Comment by brianjmiller** [comment]
I'm not able to reproduce this, but added #43 which should be correct to test it and prevent regression. Thoughts?

**Comment by garemoko** [comment]
That sounds like a sensible approach to me. @ryansmith94 do you want to re-test with the latest version?

**Comment by brianjmiller** [comment]
I merged #43 so going to close this, obviously if you spot it again and can reproduce feel free to re-open or open a new one.

**Comment by ryansmith94** [comment]
Sounds good, will do @brianjmiller thanks :+1:
