### ISSUE TITLE
Convert Statement Array to JSON

### ISSUE THREAD

**Issue by blumonkey** [RusticiSoftware/TinCanPHP#35]
I have the following simple code to fetch all statements from an LRS:

    <?php
    require '/home/blumonkey/vendor/rusticisoftware/tincan/autoload.php';
    $lrs = new TinCan\RemoteLRS(
      'http://10.17.17.163/data/xAPI/',
     '1.0.1',
     'xxxx',
     'yyyy'
      );
  
    function getAllActivity(){
       global $lrs;
      $answer=$lrs->queryStatements(null);
      return $answer;
    }
    $arr = getAllActivity()->content->getStatements();
      print_r($arr);
    ?>

I just want to send these statments back to the client JS, through AJAX, but since the statements are `protected`, I cant convert them to JSON format using json_encode. Is there a work-around?

Thanks!

**Comment by brianjmiller** [comment]
All of the model objects have an `asVersion` method that will serialize the model into an object that can be sent as JSON. So for instance:

    foreach ($arr as $st) {
        print json_encode($st->asVersion());
    }

`asVersion` optionally takes a string to indicate what version of the specification should be used for serialization.

**Comment by blumonkey** [comment]
Nice, I will try it ASAP. It would have been easier if this was mentioned in the API Documentation

**Comment by brianjmiller** [comment]
Technically it is if you know to follow the class hierarchy stuff, I don't know if there is a way to have PHP doc merge them in, as that, I agree, would be far more helpful. Reference:

http://rusticisoftware.github.io/TinCanPHP/doc/api/latest/classes/TinCan.Statement.html
extends http://rusticisoftware.github.io/TinCanPHP/doc/api/latest/classes/TinCan.StatementBase.html
has trait http://rusticisoftware.github.io/TinCanPHP/doc/api/latest/classes/TinCan.AsVersionTrait.html

Going to close this, if you still have an issue after testing please comment and re-open.

**Comment by blumonkey** [comment]
Yup, I have seen that it inherits this trait but had no clue what it does.

**Comment by brianjmiller** [comment]
Added a bit of copy to the homepage docs: https://github.com/RusticiSoftware/TinCanPHP/commit/84228a01f7f2db291e39c96581ba0cb4543f5376
