### ISSUE TITLE
Statement fails with ISO timezone specified without :

### ISSUE THREAD

**Issue by ervinMagic** [RusticiSoftware/TinCanPHP#36]
Statement fails with timestamp of 
"2015-08-06T15:26:11.274-0400"

"-04:00" is ok, "-0400" is not ISO 8601 allows either.

**Comment by garemoko** [comment]
"2015-08-06T15:26:11.274-0400" isn't valid. You can do timestamps with the punctuation or without, you can't do a combination. See http://tincanapi.com/getting-details-right-iso-8601-timestamps/
