### ISSUE TITLE
Fatal error: Uncaught exception 'Exception' with message 'Request failed: ' in /snip/src/RemoteLRS.php:123

### ISSUE THREAD

**Issue by richardtape** [RusticiSoftware/TinCanPHP#38]
Hey folks, I'm following on from @loongchan who has done some great work with our WordPress implementation of the xAPI spec using the TinCanPHP library here at UBC.

On our staging environment this morning, we had a PHP fatal error as with the title of this issue. 

https://github.com/RusticiSoftware/TinCanPHP/blob/master/src/RemoteLRS.php#L123

We don't have track_errors turned on, hence the empty message. When an `fopen()` call fails it fails with a level of E_WARNING and, as on L123 an Exception is raised, which is uncaught, this elevates that to a fatal error which is...less than ideal.

Frankly, I'm not an expert with `fopen()`, resources or streams in PHP, but I'm happy to try to work out a pull request for this issue if you'd prefer.

**Comment by brianjmiller** [comment]
@richardtape @loongchan can you take a look at #42 and see if it fixes the issue? @texdc and/or @xabbuh and/or @garemoko your thoughts are welcome for review as well.

**Comment by garemoko** [comment]
I don't recall hitting this error myself and I'm not sure how to replicate so I don't think I can be of help here. Sorry!

**Comment by brianjmiller** [comment]
@garemoko mostly just if you want to review the changes. If you don't it's okay :-).

**Comment by brianjmiller** [comment]
Should be handled by #42, please test and open an issue if still a problem. #42 will land in the next release.
