### ISSUE TITLE
Agent Data sent

### ISSUE THREAD

**Issue by abertranb** [RusticiSoftware/TinCanPHP#39]
Hello in Java version sends all data but in PHP https://github.com/RusticiSoftware/TinCanPHP/blob/master/src/Agent.php, line 48 only send one, it is ok? shoud be send everything?

Something like that

```
        if (isset($this->account)) {
            $result['account'] = $this->account->asVersion($version);
        }
        if (isset($this->mbox_sha1sum)) {
            $result['mbox_sha1sum'] = $this->mbox_sha1sum;
        }
        if (isset($this->mbox)) {
            $result['mbox'] = $this->mbox;
        }
        if (isset($this->openid)) {
            $result['openid'] = $this->openid;
        }
```

Thanks!

**Comment by garemoko** [comment]
Agents objects can only have one identifier, so possibly the Java library is missing some validation.

I encourage you to test your statements with a well established LRS that's tested with the conformance suite, such as [SCORM Cloud](http://cloud.scorm.com).

**Comment by abertranb** [comment]
Thanks for the answer, I will check
