### ISSUE TITLE
If language map is empty it gets encoded as an array rather than an object

### ISSUE THREAD

**Issue by garemoko** [RusticiSoftware/TinCanPHP#45]
```
"description" => array(
    "en-US" => null
 ),
```

The code snippet above is used to build the description of an activity. This gets rendered in JSON as ```"description":[]``` instead of  ```"description":{}```

In practice, you'd be unlikely to hard code null as the value of a language string, but null could be a possible value of some variable.

**Comment by garemoko** [comment]
This also seems to occur for

```
"description" => array(
    "en-US" => ""
 ),
```

We should allow empty strings.

**Comment by xabbuh** [comment]
You may want to use the `JSON_FORCE_OBJECT` when calling `json_encode()`.

**Comment by garemoko** [comment]
@xabbuh thanks for that suggestion, though I think that will mess with the things that should actually be arrays.

**Comment by brianjmiller** [comment]
Should be handled by #59, please test and open an issue if still a problem. #59 will land in the next release.
