### ISSUE TITLE
AsVersion removes properties containing empty strings or the number 0

### ISSUE THREAD

**Issue by garemoko** [RusticiSoftware/TinCanPHP#48]
From [StatementBase.php](https://github.com/RusticiSoftware/TinCanPHP/blob/master/src/StatementBase.php#L63)

```
if ($value !== false && empty($value)) {
    unset($result[$property]);
}
```

[empty](http://www.php.net/manual/en/function.empty.php) is too broad. This should instead be

```
if ($value === null || $value == array()) {
    unset($result[$property]);
}
```

This will allow empty strings and the number 0.

**Comment by FireGhost** [comment]
Thanks for pointing this out ! I was looking for this problem.
I would preferably use this
```php
if (empty($value) && !is_numeric($value)) {
    unset($result[$property]);
}
```
As said in [this comment](http://php.net/manual/en/function.empty.php#103756)

> When you need to accept these as valid, non-empty values:
> - 0 (0 as an integer)
> - 0.0 (0 as a float)
> - "0" (0 as a string)

**Comment by garemoko** [comment]
@FireGhost Glad to help. I prefer my solution because it also covers empty strings, the string "0" and false booleans. See http://php.net/manual/en/function.empty.php

**Comment by FireGhost** [comment]
Yes you are right, thanks again.

**Comment by sergey-rud** [comment]
#53 Fixed on this pull request. Please merge.
