### ISSUE TITLE
Get statements

### ISSUE THREAD

**Issue by Straafe** [RusticiSoftware/TinCanPHP#58]
How do I simply get statements via a TCAPI query like those generated on the SCORM Cloud? Or at least how can I get a return of all statements on the endpoint?

**Comment by brianjmiller** [comment]
You want to create an instance of `RemoteLRS` as you would to do any of the other communications with an LRS, such as saving a statement or retrieving a document (see the library home page for an example). Then you want to use the `queryStatements` and `moreStatements` methods. The former accepts an array whose properties correspond to those in the specification for `GET /statements`, sorry they aren't well documented in the API doc, you can look at the source if you need more specifics on them. The latter you would use after checking the response of the former to see if there is a more URL provided by the LRS, you then pass that to the second method recursively until you don't get one or until you have the number of statements you want.

**Comment by Straafe** [comment]
Thanks for your amazing response. I'm still making some stupid mistake, but I feel like this is almost there. The below code doesn't work, but as you can see I am just trying to get every statement with the verb "mistake"... Where can I find the exact specifications for the GET /statements? I think that's where I am going wrong.

`require 'autoload.php';

	$lrs = new TinCan\RemoteLRS(
	    'https://cloud.scorm.com/tc/N2RQA467F1/',
	    '1.0.1',
	    'tZDYOn7xA6fpc98xi3M',
	    'iIE1aWOEP0iZBjKOp4g'
	);

	 $verb = new TinCan\Verb(
	     [ 'id' => 'http://www.merriam-webster.com/dictionary/mistake' ]
	 );

	 $statement = new TinCan\Statement(
	     [
	        
	         'verb'  => $verb
	     ]
	 );

	$x=$lrs->queryStatements($statement);
	echo $x;
	echo "finished script";`

**Comment by Straafe** [comment]
It looks like I was able to get it to work by passing nothing at all through the queryStatements method, although I'd love to be able to get specific results, this is working:

`$response = $lrs->queryStatements();`

**Comment by brianjmiller** [comment]
The argument to `queryStatements` needs to be a set of filter options rather than a Statement object, unfortunately this is the part that is poorly documented at the moment. The list of possibilities in the specification is here: https://github.com/adlnet/xAPI-Spec/blob/master/xAPI.md#stmtapiget

Until this is better documented you may want to look at the function at https://github.com/RusticiSoftware/TinCanPHP/blob/master/src/RemoteLRS.php#L484 as it is what breaks down that argument to build the correct query string.

Ultimately you'll want something that looks like:

```php
$response = $lrs->queryStatements(
  [
    'verb' => $verb,
    'limit' => 25,
    ...
  ]
);
if ($response->success) {
  // TODO: handle statement list, which may be empty
  // call `moreStatements` if there is a more link
}
else {
  // TODO: handle errors
}
```

**Comment by Straafe** [comment]
Brian, with that I have gotten it working. I swear I had tried that nearly exactly, although I didn't have anything handling success or failure at the bottom which may have been breaking it. You're the absolute best, thanks for taking the time to help me.
