### ISSUE TITLE
Adding proxy parameters if necessary

### ISSUE THREAD

**Issue by deedey** [RusticiSoftware/TinCanPHP#63]
If your Moodle server  is behind a proxy server, you have to add a parameter ad-hoc like this:

        _$http = array(
            //
            // redirects are not part of the spec so LRSs shouldn't be returning them
            //
            'max_redirects' => 0,
            //
            // this is here for some proxy handling
            //
            'request_fulluri' => 1,
            **'proxy'   => '192.168.100.XXX:8080',**
            //
            // switching this to false causes non-2xx/3xx status codes to throw exceptions
            // but we need to handle the "error" status codes ourselves in some cases
            //
            'ignore_errors' => true,
            'method' => $method,
            'header' => array(
                'X-Experience-API-Version: ' . $this->version
            ),
        );_

**Comment by nadavkav** [comment]
Just came accros the same issue with Moodle using the "[xAPI LogStore](https://moodle.org/plugins/logstore_xapi)" plugin (that uses this code/library)

Thanks for the suggested fix. it helped :smile: 

I suggest improving the library code to support initiating the class with a new optional *proxy* param
so Moodle and other projects can propagate their proxy settings.

**Comment by ryansmith94** [comment]
@garemoko any idea when this might be addressed?

**Comment by garemoko** [comment]
@ryansmith94 no, but certainly sooner if somebody makes a PR. :-)

@deedey @nadavkav does one of you want to take this on?

**Comment by deedey** [comment]
@garemoko, @ryansmith94 
@nadavkav has launched a same subject in moodle-logstore_xapi. 
I think we can close this one, if you agree.

**Comment by nadavkav** [comment]
I will upload a PR, soon

**Comment by nadavkav** [comment]
@deedey Please do not close this one, as it is a dependancy to a fix I will also upload to moodle-logstore_xapi , later on.

**Comment by deedey** [comment]
As you like ,@nadavkav.

**Comment by ryansmith94** [comment]
Yeah I agree with @nadavkav, there is work to be completed in both repos so we need to keep the issues open and close them separately when the work is completed.

**Comment by nadavkav** [comment]
Thanks

**Comment by deedey** [comment]
Thank you @brianjmiller @nadavkav 
It work fine now in moodle-logstore_xapi with your both changes.
The proxy parameters are now recognized automaticly
Great thanks

**Comment by nadavkav** [comment]
Super cool :smile:
