### ISSUE TITLE
Invalid expectation of value of `score.scaled`

### ISSUE THREAD

**Issue by brianjmiller** [RusticiSoftware/TinCanPHP#74]
In https://github.com/RusticiSoftware/TinCanPHP/commit/6901caf43c0125bf5d8834162a390b06b866bf15 which landed in 0.12.0 the 'scaled' value was converted from a normal value to a "scaling factor" but this is a misinterpretation of the meaning of that value in the xAPI spec. The spec indicates the value is:

> Cf. 'cmi.score.scaled' in SCORM 2004 4th Edition

Which is a pre-calculated scaled version of the "raw" score, not a "scaling factor". As much as I appreciate that a scaling factor probably makes more sense, this lib can't automatically make that leap for the user so as part of the 1.x change I intend to remove the scaling factor nature of that handling in the `Score` class.

**Comment by brianjmiller** [comment]
@texdc this is particularly important for you. Feel free to comment, but I don't think we can keep this handling the way it is. We could "improve" the interface to include a "scaling factor" that is a separate property to get automated setting of `score.scaled` when setting `score.raw` or vice-versa, but that would go pretty far behind the "raw" nature of this lib trying to stick close to the basics of the spec.

**Comment by texdc** [comment]
IIRC, I was trying to apply the spec accurately.  That's the priority, as you have pointed out.  So, I have no problems with restoring accurate functionality.

**Comment by brianjmiller** [comment]
Fixed in #50.

**Comment by brianjmiller** [comment]
Released in 1.x.
