### ISSUE TITLE
timestamp and timezone

### ISSUE THREAD

**Issue by jbajou** [RusticiSoftware/TinCanPHP#77]
Hi guys,

Having installed the last version of TinCanPHP, I noticed that our statements had a nice 3 hours difference with our local time here in Greece, so I started to investigate.

In database I have a timestamp (so UTC) but when i access it like `$statement->getTimestamp()` it comes with a +3 for the timezone like this: `2016-09-30T15:41:14+03:00` (which sounds wrong since this is a UTC time).
I tried anyway to change the timezone of this with Carbon like this:
```php
Carbon\Carbon::parse($s->getTimestamp(), 'UTC')->timezone(config('app.timezone'))->diffForHumans()
```
but with no luck.

Timestamp in the statement are save using the `stamp()` method (which sets the UUID and the Timestamp).

Any idea about how I could fix this ?

Thanks a lot!

**Comment by garemoko** [comment]
@jbajou which version of the library are you using? Does your src/Util.php include this change: https://github.com/RusticiSoftware/TinCanPHP/pull/65/files ?

**Comment by jbajou** [comment]
Hi @garemoko thanks for your quick feedback.

I'm using `v1.0.0` and yes, it does include this. Here is the complete util:getTimestamp():
```php
public static function getTimestamp() {
        $time = microtime(true);
        $microseconds = sprintf('%06d', ($time - floor($time)) * 1000000);
        $millseconds = round($microseconds, -3)/1000;
        $millsecondsStr = str_pad($millseconds, 3, '0', STR_PAD_LEFT);
        $date = (new \DateTime(null, new \DateTimeZone("UTC")))->format('c');

        $position = strrpos($date, '+');
        $date = substr($date,0,$position).'.'.$millsecondsStr.substr($date,$position);

        return $date;
    }
```

**Comment by garemoko** [comment]
Some more diagnostic questions...

1. When you say "in database" you mean in the LRS, right? Can you get what TinCanPHP is producing to confirm whether it's using UTC (it should be). 

2. Can you check what timezone and time both the TinCanPHP and LRS servers are set to? 

3. What version of PHP are you using?

4. If you make a simple php page with the following code on your TinCanPHP server, what happens?

```php 
<?php echo(new \DateTime(null, new \DateTimeZone("UTC")))->format('c');?>
```

**Comment by jbajou** [comment]
1. I mean in the database used by my LRS. I'm the developer of the LRS, and in my case it is hosted on the same machine as the webserver (my macbook :D). If I display the result of a getTimestamp() on a statement retrieved from DB, I have this for example: "2016-09-30T15:41:14+03:00" (which is a UTC time, displayed with the +03:00 at the end, but still UTC, i.e. it was 18:41:14 when I produced that statement)

2. both set to Europe/Athens

3. php 5.6.16

4. 2016-09-30T18:02:19+00:00 (it's 21:02 local time)

Thanks for your much appreciated help

**Comment by garemoko** [comment]
On the basis of your answer to 4, I'm going to say that the problem is probably on the LRS side. TinCanPHP is just running that line of code and then appending the milliseconds, nothing more complicated and there's no way AFAIK that timestamp could get changed by TinCanPHP. 

You can confirm by testing against another LRS e.g. a free SCORM Cloud account.

**Comment by jbajou** [comment]
Here is what I tried first thing in morning today:
- I requested the LRS directly by running a SQL query, here is my timestamp:
`+"timestamp": "2016-10-03 05:51:23"`
- Did the same with TinCanPHP:
`#timestamp: "2016-10-03T05:51:23+03:00"`
My timezone has been appended, but by its definition, timestamp should be UTC if i'm not wrong.
Still investigating... Thanks for your help @garemoko

**Comment by jbajou** [comment]
Ok find it. You were right of course, the issue was coming from our LRS. We were parsing the timestamp from the database, but without specifying the timezone, which made it Europe/Athens (from the server's configuration).

Fixed now, a million thanks for your help!
