### ISSUE TITLE
Add 1.0.2 and 1.0.3 to the list of supported versions 

### ISSUE THREAD

**Issue by garemoko** [RusticiSoftware/TinCanPHP#81]
Seems like we just need to change here: 

https://github.com/RusticiSoftware/TinCanPHP/blob/522afdb16f295a49ccc8f85c89832be25ce9cad4/tests/VersionTest.php#L23-L33

and:

https://github.com/RusticiSoftware/TinCanPHP/blob/522afdb16f295a49ccc8f85c89832be25ce9cad4/src/Version.php#L35-L45

Should we modify this so that any 1.0.x version is supported?

**Comment by GrantBailey** [comment]
Andrew that sounds like a good idea.
Setting the version as 1.0.3 using the `setVersion` property of the `Statement` object seems to work for me (I use the SCORM Cloud LRS). However this may be unrelated to your question.

**Comment by WillSkates** [comment]
@garemoko Maybe introducing constraints on the version number would also be good. Is there also a need to resolve things like "v1.0.0", "1.0.0", "1" and "1.0" to the same version number?

**Comment by brianjmiller** [comment]
@WillSkates those aren't accepted version strings. I'm potentially okay to loosen any constraint on what we are reading back from an LRS (though they still have be validly formatted), but the library can't get ahead of itself with what it sends.

**Comment by garemoko** [comment]
I read that as the library accepting variant strings and translating them. I don't think that's necessary though as it's not hard for people to get the version right.

**Comment by WillSkates** [comment]
@garemoko You got it. I'd agree completely as long as there is a small list to remember. I truthfully don't know how many versions there are.

**Comment by garemoko** [comment]
0.9, 0.95, 1.0.0, 1.0.1, 1.0.2, 1.0.3

**Comment by WillSkates** [comment]
Hmm. It might be worth translating ^1.0  and ^0.9 in that case.

**Comment by brianjmiller** [comment]
Yeah, I'm not in favor of helping translate simple strings like this. xAPI is already a highly technical spec, and this library while a big help for parts of it, just shouldn't be used by people who don't understand simple versioning basics. On top of that there is a method they can call to get the actual list of all possible supported versions from the library. And finally, it defaults to `latest` so unless they are bit twiddling something specifically around versioning (in which case they need to be exceedingly precise anyways) then they don't ever actually have to interact with an actual version string.

**Comment by WillSkates** [comment]
@brianjmiller Makes perfect sense to me.

On another note do you have any idea why #82 #83 are failing? It doesn't seem to have anything to do with the code changes.

**Comment by reedmclean** [comment]
4495a4410cafcbcaaaa05dd83b426e791b84707c has taken care of this.
