### ISSUE TITLE
Statement with object definition

### ISSUE THREAD

**Issue by rena7o8** [RusticiSoftware/TinCanPHP#86]
What is the proper way to construct a statement with object definition using this library?

![image](https://cloud.githubusercontent.com/assets/26470305/25565200/e5f0cff6-2dba-11e7-9ee7-806c7b1d7cfa.png)

I want to add name and description on definition parameter, how to do it?

Any help?

**Comment by brianjmiller** [comment]
You can either instantiate a `TinCan\ActivityDefinition` instance and supply it in the array passed to the `TinCan\Activity` constructor, or simply pass an array of the values you want to that constructor and one will be constructed for you.

```
$activity = new TinCan\Activity(
  [
    'id' => $activity_id,
    'definition' => [
        'name' => '.....',
        'description' => '....'
    ]
  ]
);
```
