### ISSUE TITLE
RemoteLRS.php sendRequest not working

### ISSUE THREAD

**Issue by matt360-biz** [RusticiSoftware/TinCanPHP#88]
Hello,

Maybe someone could help me I am new to learning locker. The learning locker is installed in server 1 and we are accessing it using another system in server 2 using remoteLRS, we are able to save statements and retrieve results using sendRequest method. Now we duplicated the system in server 2 to server 3 still using the same locker in server 1, we are still able to save statements, but the retrieving of statements fail. I get this message when retrieving:

Fatal error: Uncaught exception 'Exception' with message 'Request failed:

We are still using the original system on server 2 with the same learning locker and everything works. should I be changing something to make sendRequest work on server 3?

Thank you in advance

**Comment by brianjmiller** [comment]
Did you get this sorted out? Is there a reason you are using `sendRequest` directly? If this is still reproducible I would suggest adding some additional debugging information around the call to see if you can pinpoint more of a debug message.
